name: Build MASM Programs

on:
  push:
    branches:
      - masm
  pull_request:
    branches:
      - masm
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Specific build target (leave empty for all)'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - core-only
        - demo-only
        - ai-demo-only
      debug_build:
        description: 'Enable debug symbols'
        required: false
        default: false
        type: boolean

jobs:
  build:  
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Setup MSVC Dev Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile MASM Programs
      run: |
        cd quantum-number/src/main/masm

        # Build individual programs
        ml64 /c hello_world.masm
        link hello_world.obj /subsystem:console /entry:main kernel32.lib /out:hello_world.exe

        ml64 /c QuantunNumberV8.masm
        link QuantunNumberV8.obj /subsystem:console /entry:main kernel32.lib /out:QuantunNumberV8.exe

        ml64 /c QuantumNumberV8Edition2.masm
        link QuantumNumberV8Edition2.obj /subsystem:console /entry:main kernel32.lib /out:QuantumNumberV8Edition2.exe

        # Build core library
        ml64 /c quantum_number_v8_core.masm

        # Build demo programs (multi-file)
        ml64 /c quantum_number_v8_demo.masm
        link quantum_number_v8_core.obj quantum_number_v8_demo.obj /subsystem:console /entry:main kernel32.lib user32.lib /out:quantum_number_v8_demo.exe

        # Build AI demo program
        ml64 /c quantum_number_v8_ai_demo.masm
        link quantum_number_v8_core.obj quantum_number_v8_ai_demo.obj /subsystem:console /entry:main kernel32.lib user32.lib /out:quantum_number_v8_ai_demo.exe

        # Build 1/3 + 2/3 demo program
        ml64 /c quantum_number_v8_1_3_plus_2_3_demo.masm
        link quantum_number_v8_1_3_plus_2_3_demo.obj QuantumNumberV8.obj /subsystem:console /entry:main kernel32.lib user32.lib /out:quantum_number_v8_1_3_plus_2_3_demo.exe

        # Build extended demo programs
        ml64 /c quantum_number_v8_1_3_plus_2_3_extended_demo.masm
        link quantum_number_v8_1_3_plus_2_3_extended_demo.obj QuantumNumberV8.obj /subsystem:console /entry:main kernel32.lib user32.lib /out:quantum_number_v8_1_3_plus_2_3_extended_demo.exe

        ml64 /c quantum_number_v8_1_3_plus_2_3_extended_bitwise_demo.masm
        link quantum_number_v8_1_3_plus_2_3_extended_bitwise_demo.obj QuantumNumberV8.obj /subsystem:console /entry:main kernel32.lib user32.lib /out:quantum_number_v8_1_3_plus_2_3_extended_bitwise_demo.exe

        # Build multi-precision demo programs
        ml64 /c quantum_number_v8_1_3_plus_2_3_multiprecision_demo.masm
        link quantum_number_v8_1_3_plus_2_3_multiprecision_demo.obj QuantumNumberV8.obj /subsystem:console /entry:main kernel32.lib user32.lib /out:quantum_number_v8_1_3_plus_2_3_multiprecision_demo.exe

        ml64 /c quantum_number_v8_1_3_plus_2_3_multiprecision_bitwise_demo.masm
        link quantum_number_v8_1_3_plus_2_3_multiprecision_bitwise_demo.obj QuantumNumberV8.obj /subsystem:console /entry:main kernel32.lib user32.lib /out:quantum_number_v8_1_3_plus_2_3_multiprecision_bitwise_demo.exe

    - name: Upload executables
      uses: actions/upload-artifact@v4
      with:
        name: masm-executables
        path: |
          quantum-number/src/main/masm/hello_world.exe
          quantum-number/src/main/masm/QuantunNumberV8.exe
          quantum-number/src/main/masm/QuantumNumberV8Edition2.exe
          quantum-number/src/main/masm/quantum_number_v8_demo.exe
          quantum-number/src/main/masm/quantum_number_v8_ai_demo.exe
          quantum-number/src/main/masm/quantum_number_v8_1_3_plus_2_3_demo.exe
          quantum-number/src/main/masm/quantum_number_v8_1_3_plus_2_3_extended_demo.exe
          quantum-number/src/main/masm/quantum_number_v8_1_3_plus_2_3_extended_bitwise_demo.exe
          quantum-number/src/main/masm/quantum_number_v8_1_3_plus_2_3_multiprecision_demo.exe
          quantum-number/src/main/masm/quantum_number_v8_1_3_plus_2_3_multiprecision_bitwise_demo.exe
